version: '3'
services:
  voltis:
    build: .
    ports:
      - "8080:3000"
    volumes:
      - "./data:/data"
      - "./comics:/comics"
    environment:
      - DB_URI=postgresql://barman:abcdef@postgres:5432/voltis
  postgres:
    image: postgres:16
    ports:
      - '127.0.0.1:5472:5432'
    environment:
      - POSTGRES_USER=barman
      - POSTGRES_PASSWORD=abcdef