ALTER TABLE users
    ALTER COLUMN created_at TYPE TIMESTAMPTZ,
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE sessions
    ALTER COLUMN expires_at TYPE TIMESTAMPTZ;

ALTER TABLE libraries
    ALTER COLUMN created_at TYPE TIMESTAMPTZ,
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ,
    ALTER COLUMN scanned_at TYPE TIMESTAMPTZ;

ALTER TABLE content
    ALTER COLUMN created_at TYPE TIMESTAMPTZ,
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ,
    ALTER COLUMN file_mtime TYPE TIMESTAMPTZ;

ALTER TABLE user_to_content
    ALTER COLUMN status_updated_at TYPE TIMESTAMPTZ,
    ALTER COLUMN progress_updated_at TYPE TIMESTAMPTZ;

ALTER TABLE custom_lists
    ALTER COLUMN created_at TYPE TIMESTAMPTZ,
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE custom_list_to_content
    ALTER COLUMN created_at TYPE TIMESTAMPTZ,
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE content_metadata
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE tasks
    ALTER COLUMN created_at TYPE TIMESTAMPTZ,
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ;
